### ISSUE TITLE
MirrorResources continuously failing after one build failure

### ISSUE THREAD

**Issue by atiq-cs** [statiqdev/Statiq.Web#944]
one of my build failed which I guessed left residue. Now all builds throwing this error,

    [ERRO] Content/PostProcess » RenderContentPostProcessTemplates » ExecuteIf » MirrorResources » Cannot create 'D:\a\blog\blog\output\mirror\my_cool_domain' because a file or directory with the same name already exists.
    [ERRO] Archives/PostProcess » ExecuteSwitch » RenderContentPostProcessTemplates » ExecuteIf » MirrorResources » Cannot create 'D:\a\blog\blog\output\mirror\my_cool_domain' because a file or directory with the same name already exists.

wondering how to utilize `MirrorResources: true` without making it annoying..

Thanks

https://github.com/statiqdev/Statiq.Web/blob/076c7d7e89ef1bff359352e1fcfa118b6a888f8b/src/Statiq.Web/Modules/RenderContentPostProcessTemplates.cs#L28-L31

**Comment by daveaglick** [comment]
Do happen to set `CleanOutputPath` to `false` or using the `--no-clean` CLI argument? The output folder is supposed to be cleaned after each build, though this is obviously still a bug since we need to handle uncleaned output folders gracefully. If you've got it configured not to clean, this makes total sense. If not, then my next thought it "why does a file exist there in the first place?"

Regardless, this situation should be handled. My initial thought is that the `MirrorResources` module should check if the output file exists and is the same size and skip it if it is. Another option would be to always overwrite an existing file - that's probably easier and would be "safer" since it means we're always getting the most up to date copy, but at the expense of performance since the file needs to be fetched each time.

**Comment by atiq-cs** [comment]
Hi Dave,
Thanks so much for the reply. Here are the answers,

> Do happen to set CleanOutputPath to false or using the --no-clean CLI argument?

I use default options, I do not pass the mentioned CLI argument. Here's my deploy yml,

    name: Deploy Site
    on: [push]

    jobs:
      build:
        runs-on: windows-latest
        steps:
        - name: checkout root and theme submodule
          uses: actions/checkout@master
          with:
            submodules: 'true'
        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '3.1.111' # SDK Version to use.
        - run: dotnet run -- deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by Foxtrek64** [comment]
Was a solution ever found for this? I'm running into the same error on deploy even after manually deleting the contents of the output folder. I don't set `CleanOutputPath` to `false` nor do I use the `--no-clean` argument.

**Comment by daveaglick** [comment]
Good issue bump, this one got lost a bit during the recent work with output file caching (see the latest few release notes). At the time this wasn't a critical bug since it would only happen under certain rare conditions given the default behavior was to clean everything. Now though, with all the new caching in the latest couple versions, the default behavior is not to clean all the output files so this particular issue is likely to be more common. Either way it needs a fix, but the potential to affect more folks is greater now so I'll prioritize it. Keep an eye out in the next couple days for a patch release - hopefully it won't take too much to get this resolved.

**Comment by daveaglick** [comment]
Thanks a lot for the log output @Foxtrek64. I've been digging into this and I'm actually having a really hard time reproducing it. 

The `MirrorResources` module already skips files if they exist on disk (it doesn't even need to check hashes or anything since it can be assumed mirrored CDN artifacts are immutable). In both yours and @atiq-cs case, it looks like the error is actually caused by creating the parent folder for the mirrored domain and not individual files though. That makes more sense, but I still can't reproduce locally if I delete everything locally except for the mirror folder and/or domain subfolder. I thought maybe it was an OS thing, but you're also on Windows in your CI logs, so that's not it. Anyway...still digging and hope to figure out what's causing the problem so I can fix it soon.

**Comment by Foxtrek64** [comment]
I did find this that may be of interest to you:

![unknown 1](https://user-images.githubusercontent.com/7003081/121200889-9c07b380-c863-11eb-93d7-3cc9b84398d2.png)

It seems to be outputting `output/mirror/domain` as a file, not a directory. I can name a folder ending with .com and it's still a folder. But here, it seems to be writing a file which Windows thinks is a DOS application.

**Comment by daveaglick** [comment]
I think I've figured out what's going on, and why you're only seeing it in CI @Foxtrek64. When a `Host` setting is specified, that causes links in documents to other documents be written with the host name in the link. For normal links this doesn't really manifest, but for any local link to assets, scripts, etc. the document will end up with links like "my.host.com/whatever". Since `MirrorResources` is run relatively late in the process so layouts, etc. are already processed, it sees these local links and thinks they're actually external.

Still verifying and figuring out how to fix it, but seems like that's what's going on.

**Comment by daveaglick** [comment]
I ended up fixing two things:
- `<link>` elements will only mirror if the `rel` attribute is within a known set (I.e. `rel="canonical"` links won't get mirrored since they don't point to an artifact).
- Any element where the resource to be mirrored relates to the current `Host` setting won't get mirrored.

Look for these fixes in the next release. Thanks both!
